"""Sweep the remaining hand-written score figures across docs, seeds and API examples.

Run once after sync_doc_07.py. Idempotent.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]

# (path, [(old, new), ...])
EDITS: dict[str, list[tuple[str, str]]] = {
    "docs/07-SCORING-ENGINE.md": [
        ("""gap_to_range_ratio       = max_charging_gap_km / vehicle_real_range_km
                           (route-only assessment uses the configured reference range,
                            default 120 km; an application-linked assessment uses the
                            actual financed vehicle's real_world_range_km)""",
         """gap_to_range_ratio       = max_charging_gap_km / usable_range_km
                           (a route-only assessment uses the configured reference vehicle:
                            underwriting.reference_battery_kwh = 24 kWh and
                            underwriting.reference_range_km = 140 km. An application-linked
                            assessment uses the financed vehicle's real_world_range_km.)"""),
        ("Revenue potential: `HIGH` (98.68 ≥ 75).", "Revenue potential: `HIGH` (98.67 ≥ 75)."),
        ("Charging adequacy: `ADEQUATE` (ratio 0.086 ≤ 0.6, 6 stations).",
         "Charging adequacy: `ADEQUATE` (ratio 0.0857 ≤ 0.6, 6 stations)."),
        ("| Route | Kathmandu–Dhulikhel, score **90.14**, Class A |",
         "| Route | Kathmandu–Dhulikhel, score **90.12**, Class A |"),
        ("""**Explanation (generated):** *"Kathmandu–Dhulikhel scores 90.1/100 (Class A — Low Risk). Charging
infrastructure is the strongest contributor: 6 stations across 30 km (2.0 per 10 km) including 3 DC
fast chargers, with a maximum gap of 12 km — under 9% of usable range. Demand is strong at 8
projected trips/day against 1,200 daily passengers, moderated by moderate operator competition.
The corridor is fully pitched in good condition over rolling terrain. Projected daily margin is NPR
5,267 on NPR 7,600 revenue (69%), with energy cost of NPR 2.22/km. Seasonal exposure is minimal at 6
disruption days per year. Recommendation: eligible for EV financing."*""",
         """**Explanation (generated by the engine, verbatim):** *"Kathmandu-Dhulikhel scores 90.12/100
(Class A - Low Risk). Charging Infrastructure is the strongest contributor at 91.13/100. There are 6
charging stations across 30 km (2 per 10 km) including 3 DC fast chargers, with a maximum gap of
12 km - 8.57% of the 140 km reference range, rated adequate. Demand is 8 projected trips/day with
moderate operator competition. Projected daily margin is NPR 5,266.79 on NPR 7,600.00 revenue
(69.3%), at an energy cost of NPR 2.22/km. Seasonal exposure is 6 disruption days per year."*"""),
    ],
    "docs/10-TESTING-STRATEGY.md": [
        ('    assert result.total_score == Decimal("90.14")',
         '    assert result.total_score == Decimal("90.12")'),
        ('    assert by_code["CHARGING_INFRASTRUCTURE"].normalized_score == Decimal("91.16")',
         '    assert by_code["CHARGING_INFRASTRUCTURE"].normalized_score == Decimal("91.13")'),
        ('    assert by_code["REVENUE_POTENTIAL"].normalized_score   == Decimal("98.68")',
         '    assert by_code["REVENUE_POTENTIAL"].normalized_score   == Decimal("98.67")'),
        ('    assert by_code["ROUTE_RISK"].normalized_score          == Decimal("89.23")',
         '    assert by_code["ROUTE_RISK"].normalized_score          == Decimal("89.05")'),
        ("| RS-01 | Excellent urban route | 6 stations/30 km, PITCH/GOOD, 8 trips | 90.14, Grade A |",
         "| RS-01 | Excellent urban route | 6 stations/30 km, PITCH/GOOD, 8 trips | 90.12, Grade A |"),
        ("| RS-07 | Negative margin | operating cost > revenue | Revenue component = 0, `THIN_MARGIN` |",
         "| RS-07 | Negative margin | operating cost > revenue | Revenue component collapses to 18.67 (margin and margin-ratio sub-factors clamp to 0; REVENUE_PER_KM is a gross signal and is unaffected), `THIN_MARGIN` fires |"),
        ("| CS-07 | Reference borrower | the §7.5.7 example | 75.10, Grade B |",
         "| CS-07 | Reference borrower | the §7.5.7 example | 75.17, Grade B |"),
        ("| FS-01 | Reference combined | 90.14 / 75.10 / 92.13 | 84.52, Grade B, MANUAL_REVIEW |",
         "| FS-01 | Reference combined | 90.12 / 75.17 / 90.96 | 84.31, Grade B, MANUAL_REVIEW |"),
        ("| EMI-01 | 2,960,000 @ 13% × 60 | EMI = 67,341.00 (±0.50) |",
         "| EMI-01 | 2,960,000 @ 13% × 60 | EMI = 67,349.10 (±0.50) |"),
        ("- [ ] The Kathmandu–Dhulikhel reference case returns exactly 90.14 / Grade A",
         "- [ ] The Kathmandu–Dhulikhel reference case returns exactly 90.12 / Grade A"),
    ],
    "docs/06-API-SPECIFICATION.md": [
        ('"charging_station_count": 6, "latest_score": 90.14, "latest_grade": "A",',
         '"charging_station_count": 6, "latest_score": 90.12, "latest_grade": "A",'),
        ('  "total_score": 90.14, "grade": "A", "risk_level": "LOW",',
         '  "total_score": 90.12, "grade": "A", "risk_level": "LOW",'),
        ('     "normalized_score": 91.16, "weight": 0.30, "weighted_score": 27.348,',
         '     "normalized_score": 91.13, "weight": 0.30, "weighted_score": 27.339,'),
        ('{"code": "REVENUE_POTENTIAL", "normalized_score": 98.68, "weight": 0.10, "weighted_score": 9.868, "...": "..."},',
         '{"code": "REVENUE_POTENTIAL", "normalized_score": 98.67, "weight": 0.10, "weighted_score": 9.867, "...": "..."},'),
        ('{"code": "ROUTE_RISK", "normalized_score": 89.23, "weight": 0.10, "weighted_score": 8.923, "...": "..."}',
         '{"code": "ROUTE_RISK", "normalized_score": 89.05, "weight": 0.10, "weighted_score": 8.905, "...": "..."}'),
        ('"route": {"assessment_id": "c7f2...", "score": 90.14, "grade": "A", "is_reused": true,',
         '"route": {"assessment_id": "c7f2...", "score": 90.12, "grade": "A", "is_reused": true,'),
        ('"credit_score_id": "cs44...", "total_score": 75.10, "grade": "B", "risk_level": "MODERATE",',
         '"credit_score_id": "cs44...", "total_score": 75.17, "grade": "B", "risk_level": "MODERATE",'),
        ('{"code": "VEHICLE_ECONOMICS","normalized_score": 92.13, "weight": 0.10, "weighted_score": 9.213}',
         '{"code": "VEHICLE_ECONOMICS","normalized_score": 90.96, "weight": 0.10, "weighted_score": 9.096}'),
        ('    "score": 92.13,\n    "energy_cost_per_km": 2.445,',
         '    "score": 90.96,\n    "energy_cost_per_km": 2.445,'),
        ('"final_score": 84.52, "risk_grade": "B", "risk_level": "LOW",',
         '"final_score": 84.31, "risk_grade": "B", "risk_level": "LOW",'),
        ('  "route_score": 90.14, "customer_score": 75.10,',
         '  "route_score": 90.12, "customer_score": 75.17,'),
        ('{"code": "CREDIT_HISTORY", "label": "Credit / Bureau History", "normalized_score": 85.88, "weight": 0.30, "weighted_score": 25.764 },',
         '{"code": "CREDIT_HISTORY", "label": "Credit / Bureau History", "normalized_score": 85.82, "weight": 0.30, "weighted_score": 25.746 },'),
        ('"daily_net_contribution": 6570.23,\n    "monthly_net_contribution": 168043.00,\n    "payback_months": 19.04',
         '"daily_net_contribution": 6570.22,\n    "monthly_net_contribution": 168017.61,\n    "payback_months": 19.05'),
        ('"recommended_amount": 2960000.00,\n    "max_ltv_percent": 75.00, "applied_ltv_percent": 64.35,\n    "recommended_tenure_months": 60, "recommended_interest_rate": 13.00,\n    "estimated_emi": 67341.00, "dscr": 2.495, "foir_post_loan": 0.5500,',
         '"recommended_amount": 2960000.00,\n    "max_ltv_percent": 75.00, "applied_ltv_percent": 64.35,\n    "recommended_tenure_months": 60, "recommended_interest_rate": 13.00,\n    "estimated_emi": 67349.10, "dscr": 2.4947, "foir_post_loan": 0.5500,'),
        ('"message": "Post-loan FOIR of 58.8% at the requested amount exceeds the 50% approval threshold",\n       "metric": {"name": "foir_post_loan", "value": 0.5876, "threshold": 0.50}},',
         '"message": "Post-loan FOIR of 58.77% at the requested amount exceeds the 50% approval threshold",\n       "metric": {"name": "foir_post_loan", "value": 0.5877, "threshold": 0.50}},'),
        ('"message": "Vehicle generates 2.31x the requested EMI in net contribution",\n       "metric": {"name": "dscr", "value": 2.308, "threshold": 1.30}}',
         '"message": "Vehicle generates 2.31x the requested EMI in net contribution",\n       "metric": {"name": "dscr", "value": 2.3076, "threshold": 1.30}}'),
    ],
    "docs/03-UIUX-DESIGN.md": [
        ("│   ┌───────────────────┐   │  RECOMMENDATION                                   │\n"
         "│   │   ╭─────────╮     │   │  ✅ Eligible for EV Financing                      │\n"
         "│   │  ╱   90.1    ╲    │   │  Class A — Low Risk                               │",
         "│   ┌───────────────────┐   │  RECOMMENDATION                                   │\n"
         "│   │   ╭─────────╮     │   │  ✅ Eligible for EV Financing                      │\n"
         "│   │  ╱  90.12    ╲    │   │  Class A — Low Risk                               │"),
        ("│  Charging Infrastructure  ████████████████████░  91.2 × 30%  =  27.35   [▸]   │",
         "│  Charging Infrastructure  ████████████████████░  91.13 × 30% =  27.34   [▸]   │"),
        ("│  Road Quality             ██████████████████░░░  88.3 × 20%  =  17.65   [▸]   │",
         "│  Road Quality             ██████████████████░░░  88.25 × 20% =  17.65   [▸]   │"),
        ("│  Passenger/Freight Demand ██████████████████░░░  87.9 × 30%  =  26.36   [▸]   │",
         "│  Passenger/Freight Demand ██████████████████░░░  87.85 × 30% =  26.36   [▸]   │"),
        ("│  Revenue Potential        ████████████████████░  98.7 × 10%  =   9.87   [▸]   │",
         "│  Revenue Potential        ████████████████████░  98.67 × 10% =   9.87   [▸]   │"),
        ("│  Route/Environmental Risk ██████████████████░░░  89.2 × 10%  =   8.92   [▸]   │",
         "│  Route/Environmental Risk ██████████████████░░░  89.05 × 10% =   8.91   [▸]   │"),
        ("│                                                    TOTAL  =  90.14            │",
         "│                                                    TOTAL  =  90.12            │"),
        ("│  ✓ POSITIVE FACTORS (7)          │  ⚠ RISK FACTORS (0)                        │",
         "│  ✓ POSITIVE FACTORS (6)          │  ⚠ RISK FACTORS (0)                        │"),
        ("│  \"Kathmandu–Dhulikhel scores 90.1/100 (Class A — Low Risk). Charging …\"        │",
         "│  \"Kathmandu-Dhulikhel scores 90.12/100 (Class A - Low Risk). Charging …\"       │"),
        ("│  Max gap 12 km  ·  Usable range 140 km  ·  Gap/range 8.6%  ·  Verdict Adequate  │",
         "│  Max gap 12 km  ·  Usable range 140 km  ·  Gap/range 8.57%  ·  Verdict Adequate │"),
        ("║  ▲  MANUAL REVIEW            Final Risk Score  84.5/100   ● Grade B — Low risk  ║",
         "║  ▲  MANUAL REVIEW           Final Risk Score  84.31/100   ● Grade B — Low risk  ║"),
        ("│  ROUTE      90.1  ●A     │  CUSTOMER    75.1  ●B    │  VEHICLE ECONOMICS  92.1       │\n"
         "│  × 40% = 36.06           │  × 40% = 30.04           │  × 20% = 18.43                 │",
         "│  ROUTE     90.12  ●A     │  CUSTOMER   75.17  ●B    │  VEHICLE ECONOMICS  90.96      │\n"
         "│  × 40% = 36.05           │  × 40% = 30.07           │  × 20% = 18.19                 │"),
        ("│  ⚠ HIGH   Post-loan FOIR of 58.8% exceeds the 50% approval threshold      0.588 vs 0.50│",
         "│  ⚠ HIGH   Post-loan FOIR of 58.77% exceeds the 50% approval threshold    0.5877 vs 0.50│"),
        ("│  EMI                                          NPR 72,802       NPR 67,341             │",
         "│  EMI                                          NPR 72,810       NPR 67,349             │"),
        ("│  DSCR                                              2.31             2.50   ✓ ≥1.25    │",
         "│  DSCR                                              2.31             2.49   ✓ ≥1.25    │"),
        ("│  FOIR (post-loan)                                 58.8%            55.0%   ⚠ >50%     │",
         "│  FOIR (post-loan)                                58.77%           55.00%   ⚠ >50%     │"),
        ('preview** ("NPR 67,341 → penalty 0 · interest 32,067 · principal 35,274; instalment 4 fully settled;',
         'preview** ("NPR 67,349 → penalty 0 · interest 32,067 · principal 35,282; instalment 4 fully settled;'),
    ],
    "docs/12-DEMO-FLOW.md": [
        ("1. The gauge: **90.1 / 100 · Class A · Low Risk**.",
         "1. The gauge: **90.12 / 100 · Class A · Low Risk**."),
        ("**Say:** *\"Ninety-point-one, and here is exactly why.",
         "**Say:** *\"Ninety-point-one-two, and here is exactly why."),
        ("2. The banner: **MANUAL REVIEW · Final Risk Score 84.5 / 100 · Grade B**.",
         "2. The banner: **MANUAL REVIEW · Final Risk Score 84.31 / 100 · Grade B**."),
        ("2. The three contribution cards: Route 90.1 × 40% = 36.06 · Customer 75.1 × 40% = 30.04 ·\n   Vehicle economics 92.1 × 20% = 18.43.",
         "2. The three contribution cards: Route 90.12 × 40% = 36.05 · Customer 75.17 × 40% = 30.07 ·\n   Vehicle economics 90.96 × 20% = 18.19."),
        ("4. The requested-vs-recommended table: requested NPR 32,00,000 → **recommended NPR 29,60,000**,\n   EMI NPR 72,802 → **NPR 67,341**, LTV 69.6% → 64.3%, DSCR 2.31 → 2.50.",
         "4. The requested-vs-recommended table: requested NPR 32,00,000 → **recommended NPR 29,60,000**,\n   EMI NPR 72,810 → **NPR 67,349**, LTV 69.57% → 64.35%, DSCR 2.31 → 2.49."),
        ("*\"This is the sentence that matters: a Class A route and a very strong asset do **not**\nsilently override a stretched borrower. The system says manual review, tells you precisely which\ngate failed, and tells you what would fix it. Eighty-four out of a hundred, and it still won't\nauto-approve — because the FOIR gate is 50% and he is at 58.8%.\"*",
         "*\"This is the sentence that matters: a Class A route and a very strong asset do **not**\nsilently override a stretched borrower. The system says manual review, names the single gate that\nfailed, and tells you what would fix it. Eighty-four out of a hundred, and it still won't\nauto-approve — because the FOIR gate is 50% and he is at 58.77%.\"*"),
        ("**Show:** bureau score **742**, the 24-month repayment strip (mostly green, one amber), the knock-out\nchecklist all passing, then the six-component breakdown: **75.10 / Grade B**.",
         "**Show:** bureau score **742**, the 24-month repayment strip (mostly green, one amber), the knock-out\nchecklist all passing, then the six-component breakdown: **75.17 / Grade B**."),
        ("**Say:** *\"Strong credit history at 85.9, strong vehicle economics at 92.1 — but existing debt scores\nonly 58.7. Hold that thought.\"*",
         "**Say:** *\"Strong credit history at 85.8, strong vehicle economics at 90.96 — but existing debt scores\nonly 61.7. Hold that thought.\"*"),
        ("| Route score | Cust. score | **Final** |", "| Route score | Cust. score | **Final** |"),
    ],
    "api-examples/route-assess-response.json": [
        ('"total_score": 90.14,', '"total_score": 90.12,'),
        ('"normalized_score": 91.16,\n      "weight": 0.30,\n      "weighted_score": 27.348,',
         '"normalized_score": 91.13,\n      "weight": 0.30,\n      "weighted_score": 27.339,'),
        ('{ "code": "MAX_GAP_VS_RANGE", "value": 0.0857, "score": 96.9, "weight": 0.35, "contribution": 33.91 },',
         '{ "code": "MAX_GAP_VS_RANGE", "value": 0.085714, "score": 96.79, "weight": 0.35, "contribution": 33.875 },'),
        ('{ "code": "STATION_DENSITY", "value": 2.0, "score": 90.0, "weight": 0.40, "contribution": 36.00 },',
         '{ "code": "STATION_DENSITY", "value": 2.0, "score": 90.00, "weight": 0.40, "contribution": 36.000 },'),
        ('{ "code": "FAST_CHARGER_SHARE", "value": 0.5, "score": 85.0, "weight": 0.25, "contribution": 21.25 }',
         '{ "code": "FAST_CHARGER_SHARE", "value": 0.5, "score": 85.00, "weight": 0.25, "contribution": 21.250 }'),
        ('"normalized_score": 98.68,\n      "weight": 0.10,\n      "weighted_score": 9.868,',
         '"normalized_score": 98.67,\n      "weight": 0.10,\n      "weighted_score": 9.867,'),
        ('"normalized_score": 89.23,\n      "weight": 0.10,\n      "weighted_score": 8.923,',
         '"normalized_score": 89.05,\n      "weight": 0.10,\n      "weighted_score": 8.905,'),
        ('"reference_range_km": 380,\n    "gap_to_range_ratio": 0.0857,',
         '"reference_range_km": 140,\n    "gap_to_range_ratio": 0.085714,'),
        ('"_request": { "reference_vehicle_model_id": 6, "notes": "Initial assessment" },',
         '"_request": { "notes": "Initial assessment" },'),
        ('"estimated_monthly_profit": 136934.72,', '"estimated_monthly_profit": 136936.50,'),
    ],
    "api-examples/application-assess-response.json": [
        ('"score": 90.14,\n    "grade": "A",', '"score": 90.12,\n    "grade": "A",'),
        ('"total_score": 75.10,', '"total_score": 75.17,'),
        ('"normalized_score": 85.88, "weight": 0.30, "weighted_score": 25.764 }',
         '"normalized_score": 85.82, "weight": 0.30, "weighted_score": 25.746 }'),
        ('"normalized_score": 65.21, "weight": 0.25, "weighted_score": 16.303 }',
         '"normalized_score": 64.43, "weight": 0.25, "weighted_score": 16.108 }'),
        ('"normalized_score": 58.73, "weight": 0.15, "weighted_score": 8.810 }',
         '"normalized_score": 61.66, "weight": 0.15, "weighted_score": 9.249 }'),
        ('"normalized_score": 68.70, "weight": 0.10, "weighted_score": 6.870 }',
         '"normalized_score": 68.74, "weight": 0.10, "weighted_score": 6.874 }'),
        ('"normalized_score": 81.40, "weight": 0.10, "weighted_score": 8.140 }',
         '"normalized_score": 81.00, "weight": 0.10, "weighted_score": 8.100 }'),
        ('"normalized_score": 92.13, "weight": 0.10, "weighted_score": 9.213 }',
         '"normalized_score": 90.96, "weight": 0.10, "weighted_score": 9.096 }'),
        ('"score": 92.13,\n    "energy_cost_per_km": 2.445,', '"score": 90.96,\n    "energy_cost_per_km": 2.445,'),
        ('"daily_net_contribution": 6570.23,', '"daily_net_contribution": 6570.22,'),
        ('"seasonal_factor": 0.98356,', '"seasonal_factor": 0.98356,'),
        ('"monthly_net_contribution": 168043.00,', '"monthly_net_contribution": 168017.61,'),
        ('"payback_months": 19.04', '"payback_months": 19.05'),
        ('"final_score": 84.52,', '"final_score": 84.31,'),
        ('"contributions": { "route": 36.056, "customer": 30.040, "vehicle": 18.426 },',
         '"contributions": { "route": 36.048, "customer": 30.068, "vehicle": 18.192 },'),
        ('"emi": 72802.00,\n      "dscr": 2.308,\n      "foir_post_loan": 0.5876,\n      "ltv_percent": 69.57',
         '"emi": 72809.83,\n      "dscr": 2.3076,\n      "foir_post_loan": 0.587654,\n      "ltv_percent": 69.5652'),
        ('"emi": 67341.00,\n      "max_ltv_percent": 75.00,\n      "applied_ltv_percent": 64.35,\n      "dscr": 2.495,',
         '"emi": 67349.10,\n      "max_ltv_percent": 75.00,\n      "applied_ltv_percent": 64.35,\n      "dscr": 2.4947,'),
        ('"payback_months": 19.04\n    },', '"payback_months": 19.05\n    },'),
        ('"message": "Post-loan FOIR of 58.8% at the requested amount exceeds the 50% approval threshold",',
         '"message": "Post-loan FOIR of 58.77% at the requested amount exceeds the 50% approval threshold",'),
        ('"metric": { "name": "foir_post_loan", "value": 0.5876, "threshold": 0.50 }',
         '"metric": { "name": "foir_post_loan", "value": 0.587654, "threshold": 0.50 }'),
        ('"message": "Disposable income barely covers the requested EMI (coverage 1.00x)",',
         '"message": "Disposable income covers the proposed EMI only 1.00x",'),
        ('"metric": { "name": "disposable_to_emi_ratio", "value": 0.997, "threshold": 1.30 }',
         '"metric": { "name": "disposable_to_emi_ratio", "value": 0.99712, "threshold": 1.30 }'),
        ('"metric": { "name": "dscr", "value": 2.308, "threshold": 1.30 }',
         '"metric": { "name": "dscr", "value": 2.3076, "threshold": 1.30 }'),
        ('"metric": { "name": "route_score", "value": 90.14, "threshold": 80.0 }',
         '"metric": { "name": "route_score", "value": 90.12, "threshold": 80.0 }'),
        ('"metric": { "name": "down_payment_ratio", "value": 0.3043, "threshold": 0.20 }',
         '"metric": { "name": "down_payment_ratio", "value": 0.304348, "threshold": 0.20 }'),
        ('"message": "Route Kathmandu-Dhulikhel is Class A with adequate charging infrastructure",',
         '"message": "Route is Class A with a score of 90.12",'),
    ],
}

SETTINGS_EDITS = [
    ("db/seed/01_reference_data.sql",
     [("('underwriting.reference_range_km','120','NUMBER','UNDERWRITING','Reference vehicle range (km)','Used for route assessment when no vehicle is specified.',50,600),",
       "('underwriting.reference_range_km','140','NUMBER','UNDERWRITING','Reference vehicle range (km)','Usable range of the reference vehicle, used for route assessment when no financed vehicle is specified.',50,600),\n ('underwriting.reference_battery_kwh','24','NUMBER','UNDERWRITING','Reference vehicle battery (kWh)','Battery capacity of the reference vehicle, used for the route energy-cost calculation.',5,200),")]),
]


def apply(rel: str, pairs: list[tuple[str, str]]) -> None:
    path = ROOT / rel
    if not path.exists():
        print(f"  !! missing {rel}")
        return
    text = path.read_text(encoding="utf-8")
    hits = misses = 0
    for old, new in pairs:
        if old in text:
            text = text.replace(old, new)
            hits += 1
        else:
            misses += 1
    path.write_text(text, encoding="utf-8")
    status = f"{hits} applied" + (f", {misses} not found" if misses else "")
    print(f"  {rel}: {status}")


def main() -> None:
    print("syncing residual figures:")
    for rel, pairs in EDITS.items():
        apply(rel, pairs)
    for rel, pairs in SETTINGS_EDITS:
        apply(rel, pairs)

    # validate the JSON examples still parse
    for name in ("route-assess-response.json", "application-assess-response.json"):
        p = ROOT / "api-examples" / name
        json.loads(p.read_text(encoding="utf-8"))
        print(f"  {name}: valid JSON")


if __name__ == "__main__":
    main()
